-- COMPREHENSIVE SCHEMA FIX FOR ALL DATABASES
-- This script fixes column order, types, and removes redundant columns

-- Step 1: Fix superpixel_visitors table
-- Create new table with correct structure
CREATE TABLE superpixel_visitors_new (
    uuid varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci NOT NULL,
    first_name varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    last_name varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_city varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_state varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_zip varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_zip4 varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    age_range varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    children varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    gender varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    homeowner varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    married varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    net_worth varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    income_range varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    direct_number text CHARACTER SET utf32 COLLATE utf32_general_ci,
    direct_number_dnc varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    mobile_phone text CHARACTER SET utf32 COLLATE utf32_general_ci,
    mobile_phone_dnc varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_phone text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_phone_dnc varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    business_email text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_emails text CHARACTER SET utf32 COLLATE utf32_general_ci,
    deep_verified_emails text CHARACTER SET utf32 COLLATE utf32_general_ci,
    sha256_personal_email longtext CHARACTER SET utf32 COLLATE utf32_general_ci,
    sha256_business_email longtext CHARACTER SET utf32 COLLATE utf32_general_ci,
    hem_sha256 text CHARACTER SET utf32 COLLATE utf32_general_ci,
    job_title text CHARACTER SET utf32 COLLATE utf32_general_ci,
    headline text CHARACTER SET utf32 COLLATE utf32_general_ci,
    department varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    seniority_level varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    inferred_years_experience varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_name_history text CHARACTER SET utf32 COLLATE utf32_general_ci,
    job_title_history text CHARACTER SET utf32 COLLATE utf32_general_ci,
    education_history text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_description text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_domain varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_employee_count varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_linkedin_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_name varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_phone varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_revenue varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_sic varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_naics varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_city varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_state varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_zip varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_industry varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    linkedin_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    twitter_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    facebook_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    social_connections text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skills text CHARACTER SET utf32 COLLATE utf32_general_ci,
    interests text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_match_score varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_name varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_city varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_state varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_zip varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_landline_numbers text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_wireless_numbers text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_credit_rating varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_dnc varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_exact_age varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_ethnic_code varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_language_code varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_ip varchar(45) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_b2b_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_b2b_phone varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_b2b_source text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_b2b_website text CHARACTER SET utf32 COLLATE utf32_general_ci,
    valid_phones text CHARACTER SET utf32 COLLATE utf32_general_ci,
    first_seen_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    event_count int DEFAULT 0,
    -- CORRECTED fields - matching superpixel_resolution_log naming for easy mapping
    url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    element text CHARACTER SET utf32 COLLATE utf32_general_ci,
    percentage int DEFAULT NULL,
    referrer text CHARACTER SET utf32 COLLATE utf32_general_ci,
    event_timestamp varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    event_type varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    npn varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    crd varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    PRIMARY KEY (uuid),
    KEY idx_uuid (uuid),
    KEY idx_hem_sha256 (hem_sha256(255)),
    KEY idx_sha256_personal_email (sha256_personal_email(255)),
    KEY idx_company_domain (company_domain),
    KEY idx_name (last_name, first_name),
    KEY idx_last_seen_at (last_seen_at),
    KEY idx_npn (npn),
    KEY idx_crd (crd)
) ENGINE=InnoDB DEFAULT CHARSET=utf32;

-- Step 2: Fix superpixel_resolution_log table (remove redundant 'elements' column)
CREATE TABLE superpixel_resolution_log_new (
    id int NOT NULL AUTO_INCREMENT,
    uuid varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    first_name varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    last_name varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    event_timestamp varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    event_type varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    hem_sha256 text CHARACTER SET utf32 COLLATE utf32_general_ci,
    ip_address varchar(45) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    pixel_id varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    activity_start_date varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    activity_end_date varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    referrer_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_city varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_state varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_zip varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_zip4 varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    age_range varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    children varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    gender varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    homeowner varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    married varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    net_worth varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    income_range varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    direct_number text CHARACTER SET utf32 COLLATE utf32_general_ci,
    direct_number_dnc varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    mobile_phone text CHARACTER SET utf32 COLLATE utf32_general_ci,
    mobile_phone_dnc varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    personal_phone text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_phone_dnc varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    business_email text CHARACTER SET utf32 COLLATE utf32_general_ci,
    personal_emails text CHARACTER SET utf32 COLLATE utf32_general_ci,
    deep_verified_emails text CHARACTER SET utf32 COLLATE utf32_general_ci,
    sha256_personal_email longtext CHARACTER SET utf32 COLLATE utf32_general_ci,
    sha256_business_email longtext CHARACTER SET utf32 COLLATE utf32_general_ci,
    job_title text CHARACTER SET utf32 COLLATE utf32_general_ci,
    headline text CHARACTER SET utf32 COLLATE utf32_general_ci,
    department varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    seniority_level varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    inferred_years_experience varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_name_history text CHARACTER SET utf32 COLLATE utf32_general_ci,
    job_title_history text CHARACTER SET utf32 COLLATE utf32_general_ci,
    education_history text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_description text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_domain varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_employee_count varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_linkedin_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    company_name varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_phone varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_revenue varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_sic varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_naics varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_city varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_state varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_zip varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    company_industry varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    linkedin_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    twitter_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    facebook_url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    social_connections text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skills text CHARACTER SET utf32 COLLATE utf32_general_ci,
    interests text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_match_score varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_name varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_city varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_state varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_zip varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_landline_numbers text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_wireless_numbers text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_credit_rating varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_dnc varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_exact_age varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_ethnic_code varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_language_code varchar(50) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_ip varchar(45) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_b2b_address text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_b2b_phone varchar(20) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    skiptrace_b2b_source text CHARACTER SET utf32 COLLATE utf32_general_ci,
    skiptrace_b2b_website text CHARACTER SET utf32 COLLATE utf32_general_ci,
    element text CHARACTER SET utf32 COLLATE utf32_general_ci,
    percentage varchar(10) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    referrer text CHARACTER SET utf32 COLLATE utf32_general_ci,
    timestamp varchar(100) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    title text CHARACTER SET utf32 COLLATE utf32_general_ci,
    url text CHARACTER SET utf32 COLLATE utf32_general_ci,
    valid_phones text CHARACTER SET utf32 COLLATE utf32_general_ci,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    npn varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    crd varchar(255) CHARACTER SET utf32 COLLATE utf32_general_ci DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_uuid (uuid),
    KEY idx_event_timestamp (event_timestamp),
    KEY idx_url (url(255)),
    KEY idx_hem_sha256 (hem_sha256(255)),
    KEY idx_sha256_personal_email (sha256_personal_email(255)),
    KEY idx_pixel_id (pixel_id),
    KEY idx_company_domain (company_domain),
    KEY idx_name (last_name, first_name),
    KEY idx_npn (npn),
    KEY idx_crd (crd)
) ENGINE=InnoDB DEFAULT CHARSET=utf32;

-- Data migration scripts will be generated per database 